#yoapy.hex: pearl100.c yoapy.c yoapy.h simpleList.c simpleList.h
#	gcc simpleList.c simpleList.h yoapy.c yoapy.h pearl100.c -o yoapy.hex
all: digservice.jndevkit.hex

TARGET=jndevkit

PROJECT_SOURCEFILES = mdns.c coap.c

UIP_CONF_IPV6=1

CONTIKI = ../..
include $(CONTIKI)/Makefile.include



#clean:
#	rm -fr *.o yoapy.hex *.ghc
